# Generated by Django 6.0.2 on 2026-03-09 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('roommates_count', models.PositiveIntegerField()),
                ('roommates_looking_for_number', models.PositiveIntegerField()),
                ('total_rooms', models.PositiveIntegerField()),
                ('gender_preference', models.CharField(choices=[('GIRLS', 'Girls'), ('BOYS', 'Boys'), ('ALL', 'All')], default='ALL', max_length=10)),
                ('smoking', models.BooleanField(default=False)),
                ('pets', models.BooleanField(default=False)),
                ('visibility', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'property_listings',
            },
        ),
        migrations.CreateModel(
            name='PropertyListingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='listing_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.propertylisting')),
            ],
            options={
                'db_table': 'property_listing_images',
            },
        ),
    ]
