# Generated by Django 6.0.2 on 2026-03-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_age_customuser_bio_customuser_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='isOwner',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='isUser',
        ),
    ]
